<template>
  <v-container>


    <v-expansion-panels
        v-for="(curriculum, i) in curriculum_details"
        :key="i"
        class="my-3"
        color="pink lighten-5"
        elevation="2"
    >
      <v-expansion-panel>
        <v-expansion-panel-header>
          <v-col cols="11">
            <h2>Week {{ curriculum.week }}: {{ curriculum.name }}</h2>
          </v-col>
          <v-col cols="1">
            <EditCurriculum :curriculum_detail="curriculum"></EditCurriculum>
          </v-col>
        </v-expansion-panel-header>

        <v-expansion-panel-content>
          <v-list-item :href="curriculum.documentation" target="_blank">Documentation: {{
              curriculum.name
            }}
          </v-list-item>
          <v-list-item :href="curriculum.student_link" target="_blank">Student Project: {{
              curriculum.name
            }}
          </v-list-item>
          <v-list-item :href="curriculum.teacher_link" target="_blank">Teacher Project: {{
              curriculum.name
            }}
          </v-list-item>
        </v-expansion-panel-content>

      </v-expansion-panel>
    </v-expansion-panels>
  </v-container>
</template>

<script>
import {curriculum_details} from "@/components/curriculum/CurriculumData";
import {dataBase} from "@/backend/backend";
import EditCurriculum from "@/components/curriculum/EditCurriculum";

export default {
  name: "CurriculumContent",
  components: {
    EditCurriculum
  },
  data() {
    return {
      curriculum_details,
    }
  },

  created() {
    dataBase.collection("curriculum").onSnapshot(res => {
      const changes = res.docChanges()
      changes.forEach(change => {

        if (change.type === 'added') {
          curriculum_details.push({
            ...change.doc.data(),
            id: change.doc.id, //custom id generated by firebase
          })
        }
      })
    })
  }
}
</script>

