import firebase from 'firebase'

const dataBase = firebase.firestore()

function hasSameDoc(localCollection, incomingObject) {
    return !!localCollection.some(localDoc => localDoc.id === incomingObject.doc.id);
}

function getCollection(collection, targetArray) {
    dataBase.collection(collection).onSnapshot(res => {

        const changes = res.docChanges()
        changes.forEach(change => {

            if (change.type === 'added' && !hasSameDoc(targetArray, change)) {
                targetArray.push({
                    ...change.doc.data(),
                    id: change.doc.id, //custom id generated by firebase
                })

                console.log("Change in Data")
            }
        })
    })
}


export {dataBase, getCollection}